/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservation;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
//Array in which user data will be retrived
import java.sql.ResultSet;
import javax.swing.Action;
import javax.swing.JFrame;
import javax.swing.UIManager;
/**
 *
 * @author Hassan Mansour
 */
public class main_app extends javax.swing.JFrame {

    /**
     * Creates new form main_app
     */
    public main_app() {
       
        initComponents();
        setLocationRelativeTo(null);
        setTitle("OBM registeration");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPanel3 = new javax.swing.JPanel();
        input_data = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        search = new javax.swing.JButton();
        show = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(62, 62, 62));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(62, 62, 62));

        input_data.setAction(search.getAction());
        input_data.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        input_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_dataActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Enter Ticket Serial");

        search.setBackground(new java.awt.Color(255, 11, 162));
        search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Enter Ticket");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        show.setBackground(new java.awt.Color(255, 207, 6));
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setText("Show Details");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        show.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                showPropertyChange(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("© Eng. Muhammed Taha ");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("01142747666");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(input_data, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(show)))
                        .addGap(0, 101, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(input_data, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        input_data.getAccessibleContext().setAccessibleName("");

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu2.setText("Actions");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("show details");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        jMenuItem3.setText("Enter ticket");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    /**
     *
     */
    /*public String seta (){
    String a = usr_name.getText();
    return a;
    }*/
    public static String name,number,e;
    
    public String set1 (){
        return name;
        
    }
    public String set2 (){
        
        return number;
    }
    public String set3 (){
        return e;
        
    }
    
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        
        
        
        PreparedStatement pstmt;
        PreparedStatement pstmt1;
        PreparedStatement pstmt2;
        ResultSet rs;
        ResultSet rs1;
        String num = input_data.getText();
        
        String query1 ="update newone set `entered`='1' WHERE `Tticket_code`=?";
        String query ="SELECT `Name`, `entered` , `number` FROM `newone` WHERE `Tticket_code`=?";
        String query2="SELECT `entered` FROM `newone` WHERE `Tticket_code`=?";
        
        
        
        try{
            pstmt= MyConnection.getConnection().prepareStatement(query);
            
            pstmt.setString(1, num);
            
            rs= pstmt.executeQuery();
            
            if(rs.next()){
              name = rs.getString("Name");
              number = rs.getString("number");
              e=rs.getString("entered");
             /* NewJFrame jf = new NewJFrame();
              jf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           
              jf.setVisible(true);*/
              /*usr_name.setText(name);
              ticket_num.setText(number);
              entered.setText(e);*/
                
             
              
             
              }
            
                    
            else{
               JOptionPane.showMessageDialog(null, "Ticket Not Found!\n a2fe4 7aramii!!!!");}
        
        }catch(SQLException | HeadlessException ex){
            System.out.println(ex.getMessage());
        }
        
        try{
            pstmt2= MyConnection.getConnection().prepareStatement(query2);
            
            pstmt2.setString(1, num);
            
            rs1= pstmt2.executeQuery();
            
            if(rs1.next()){
                String e1=rs1.getString("entered");
                
                if("0".equals(e1)){
                JOptionPane.showMessageDialog(null, "Ticket is good to go");
                pstmt1= MyConnection.getConnection().prepareStatement(query1);
                pstmt1.setString(1,num);
                pstmt1.executeUpdate();
               
                
            }else{
                UIManager UI=new UIManager();
                    UI.put("OptionPane.background", Color.red);
                    UI.put("Panel.background", Color.red);

                    JOptionPane.showMessageDialog(null,"Warning:\nTicket already entered","Warning",JOptionPane.WARNING_MESSAGE);
                
                }
            
            }
        }
        catch(SQLException | HeadlessException ex){
            System.out.println(ex.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchKeyPressed

    private void input_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_dataActionPerformed
        // TODO add your handling code here:
         PreparedStatement pstmt;
        PreparedStatement pstmt1;
        PreparedStatement pstmt2;
        ResultSet rs;
        ResultSet rs1;
        String num = input_data.getText();
        
        String query1 ="update newone set `entered`='1' WHERE `Tticket_code`=?";
        String query ="SELECT `Name`, `entered` , `number` FROM `newone` WHERE `Tticket_code`=?";
        String query2="SELECT `entered` FROM `newone` WHERE `Tticket_code`=?";
        
        
        
        try{
            pstmt= MyConnection.getConnection().prepareStatement(query);
            
            pstmt.setString(1, num);
            
            rs= pstmt.executeQuery();
            
            if(rs.next()){
              name = rs.getString("Name");
              number = rs.getString("number");
              e=rs.getString("entered");
             /* NewJFrame jf = new NewJFrame();
              jf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           
              jf.setVisible(true);*/
              /*usr_name.setText(name);
              ticket_num.setText(number);
              entered.setText(e);*/
                
             
              
             
              }
            
                    
            else{
               JOptionPane.showMessageDialog(null, "Ticket Not Found!\n a2fe4 7aramii!!!!");}
        
        }catch(SQLException | HeadlessException ex){
            System.out.println(ex.getMessage());
        }
        
        try{
            pstmt2= MyConnection.getConnection().prepareStatement(query2);
            
            pstmt2.setString(1, num);
            
            rs1= pstmt2.executeQuery();
            
            if(rs1.next()){
                String e1=rs1.getString("entered");
                
                if("0".equals(e1)){
                JOptionPane.showMessageDialog(null, "Ticket is good to go");
                pstmt1= MyConnection.getConnection().prepareStatement(query1);
                pstmt1.setString(1,num);
                pstmt1.executeUpdate();
               
                
            }else{
                    UIManager UI=new UIManager();
                    UI.put("OptionPane.background", Color.red);
                    UI.put("Panel.background", Color.red);

                    JOptionPane.showMessageDialog(null,"Warning:\nTicket already entered","Warning",JOptionPane.WARNING_MESSAGE);
                    
                //JOptionPane.showMessageDialog(null, "Warning:\nTicket already entered","Warning",JOptionPane.WARNING_MESSAGE);
                
                }
            
            }
        }
        catch(SQLException | HeadlessException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_input_dataActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
       
        PreparedStatement pstmt;
        PreparedStatement pstmt1;
        PreparedStatement pstmt2;
        ResultSet rs;
        ResultSet rs1;
        String num = input_data.getText();
        
        
        String query ="SELECT `Name`, `entered` , `number` FROM `newone` WHERE `Tticket_code`=?";
        String query2="SELECT `entered` FROM `newone` WHERE `Tticket_code`=?";
        
        
        
        try{
            pstmt= MyConnection.getConnection().prepareStatement(query);
            
            pstmt.setString(1, num);
            
            rs= pstmt.executeQuery();
            
            if(rs.next()){
              name = rs.getString("Name");
              number = rs.getString("number");
              e=rs.getString("entered");
              NewJFrame jf = new NewJFrame();
              jf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           
              jf.setVisible(true);
              /*usr_name.setText(name);
              ticket_num.setText(number);
              entered.setText(e);*/
                
             
              
             
              }
            
                    
            else{
               JOptionPane.showMessageDialog(null, "Ticket Not Found!\n a2fe4 7aramii!!!!");}
        
        }catch(SQLException | HeadlessException ex){
            System.out.println(ex.getMessage());
        }
        
       

// TODO add your handling code here:
    }//GEN-LAST:event_showActionPerformed

    private void showPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_showPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_showPropertyChange

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        PreparedStatement pstmt;
        PreparedStatement pstmt1;
        PreparedStatement pstmt2;
        ResultSet rs;
        ResultSet rs1;
        String num = input_data.getText();
        
        
        String query ="SELECT `Name`, `entered` , `number` FROM `newone` WHERE `Tticket_code`=?";
        String query2="SELECT `entered` FROM `newone` WHERE `Tticket_code`=?";
        
        
        
        try{
            pstmt= MyConnection.getConnection().prepareStatement(query);
            
            pstmt.setString(1, num);
            
            rs= pstmt.executeQuery();
            
            if(rs.next()){
              name = rs.getString("Name");
              number = rs.getString("number");
              e=rs.getString("entered");
              NewJFrame jf = new NewJFrame();
              jf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           
              jf.setVisible(true);
              /*usr_name.setText(name);
              ticket_num.setText(number);
              entered.setText(e);*/
                
             
              
             
              }
            
                    
            else{
               JOptionPane.showMessageDialog(null, "Ticket Not Found!\n a2fe4 7aramii!!!!");}
        
        }catch(SQLException | HeadlessException ex){
            System.out.println(ex.getMessage());
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        PreparedStatement pstmt;
        PreparedStatement pstmt1;
        PreparedStatement pstmt2;
        ResultSet rs;
        ResultSet rs1;
        String num = input_data.getText();
        
        String query1 ="update newone set `entered`='1' WHERE `Tticket_code`=?";
        String query ="SELECT `Name`, `entered` , `number` FROM `newone` WHERE `Tticket_code`=?";
        String query2="SELECT `entered` FROM `newone` WHERE `Tticket_code`=?";
        
        
        
        try{
            pstmt= MyConnection.getConnection().prepareStatement(query);
            
            pstmt.setString(1, num);
            
            rs= pstmt.executeQuery();
            
            if(rs.next()){
              name = rs.getString("Name");
              number = rs.getString("number");
              e=rs.getString("entered");
             /* NewJFrame jf = new NewJFrame();
              jf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           
              jf.setVisible(true);*/
              /*usr_name.setText(name);
              ticket_num.setText(number);
              entered.setText(e);*/
                
             
              
             
              }
            
                    
            else{
               JOptionPane.showMessageDialog(null, "Ticket Not Found!\n a2fe4 7aramii!!!!");}
        
        }catch(SQLException | HeadlessException ex){
            System.out.println(ex.getMessage());
        }
        
        try{
            pstmt2= MyConnection.getConnection().prepareStatement(query2);
            
            pstmt2.setString(1, num);
            
            rs1= pstmt2.executeQuery();
            
            if(rs1.next()){
                String e1=rs1.getString("entered");
                
                if("0".equals(e1)){
                JOptionPane.showMessageDialog(null, "Ticket is good to go");
                pstmt1= MyConnection.getConnection().prepareStatement(query1);
                pstmt1.setString(1,num);
                pstmt1.executeUpdate();
               
                
            }else{
                JOptionPane.showMessageDialog(null, "Warning:\nTicket already entered");
                
                }
            
            }
        }
        catch(SQLException | HeadlessException ex){
            System.out.println(ex.getMessage());
        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                } else {
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_app().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input_data;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label label1;
    private javax.swing.JButton search;
    private javax.swing.JButton show;
    // End of variables declaration//GEN-END:variables
}
